### ISSUE TITLE
`No such file or directory: '/sys/devices/platform/switchboard/SFF/QSFP33/qsfp_isr_flags'`

### ISSUE THREAD

**Issue by bluecmd** [kamelnetworks/sonic-buildimage#1]
On celestica seastone_2:

```
Jan 14 08:51:36.081092 ixp-kg-sw1 WARNING pmon#xcvrd[240266]: Could not retreive port inside config_db PORT table 
Jan 14 08:51:36.225893 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd Process Process-1:
Jan 14 08:51:36.226263 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd Traceback (most recent call last):
Jan 14 08:51:36.226518 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd   File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Jan 14 08:51:36.226730 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd     self.run()
Jan 14 08:51:36.226936 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Jan 14 08:51:36.227231 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd     self._target(*self._args, **self._kwargs)
Jan 14 08:51:36.227851 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/xcvrd/xcvrd.py", line 1060, in task_worker
Jan 14 08:51:36.228128 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd     status, port_dict = _wrapper_get_transceiver_change_event(timeout)
Jan 14 08:51:36.228340 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/xcvrd/xcvrd.py", line 210, in _wrapper_get_transceiver_change_event
Jan 14 08:51:36.228547 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd     status, events = platform_chassis.get_change_event(timeout)
Jan 14 08:51:36.228753 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/sonic_platform/chassis.py", line 255, in get_change_event
Jan 14 08:51:36.228960 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd     return self._api_common.get_event(timeout, self._config['get_change_event'], self._sfp_list)
Jan 14 08:51:36.229180 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/sonic_platform/common.py", line 283, in get_event
Jan 14 08:51:36.229411 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd     return event_class(sfp_list).get_event(timeout)
Jan 14 08:51:36.229620 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd   File "/usr/share/sonic/platform/sonic_platform_config/event.py", line 99, in get_event
Jan 14 08:51:36.229828 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd     chk_sfp = self._check_all_port_interrupt_event()
Jan 14 08:51:36.230033 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd   File "/usr/share/sonic/platform/sonic_platform_config/event.py", line 86, in _check_all_port_interrupt_event
Jan 14 08:51:36.230241 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd     interrupt_flags = self._api_common.read_txt_file(int_sysfs)
Jan 14 08:51:36.230486 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd   File "/usr/local/lib/python2.7/dist-packages/sonic_platform/common.py", line 156, in read_txt_file
Jan 14 08:51:36.230692 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd     with open(path, 'r') as f:
Jan 14 08:51:36.230895 ixp-kg-sw1 INFO pmon#/supervisord: xcvrd IOError: [Errno 2] No such file or directory: '/sys/devices/platform/switchboard/SFF/QSFP33/qsfp_isr_flags'

```

Likely some SFP1 logic still missing.

**Comment by bluecmd** [comment]
`/usr/share/sonic/device/x86_64-cel_seastone_2-r0/sonic_platform_config/sfp.json` has these references it seems

**Comment by bluecmd** [comment]
`/sys/devices/platform/switchboard/SFF/` is a symlink to `/sys/devices/virtual/seastone2_fpga/sff_device` so that's fine.
It's the name of QSFP33 that is wrong.

**Comment by bluecmd** [comment]
Fixed in https://github.com/kamelnetworks/sonic-buildimage/commit/639044b8a16c5562128f5c53b489be70728ff94a and https://github.com/kamelnetworks/sonic-buildimage/commit/3a502f8396e091b6e63cba012e8ded952a4050ab
